/* Section 2 rebuilt: 4-mode option chain + trade-from-chart.
 *
 * Same contract as improve.js — applied after React hydrates, idempotent, and
 * re-tried on an interval so a re-render cannot duplicate or lose it. Kept in
 * its own file because improve.js is regenerated by the imp_s1* scripts.
 *
 * Every number quoted in the copy below is read off the screenshots in
 * tradepro-shots/, which are all the same tick (NIFTY 24471.7, 11 Aug 2026
 * expiry, +/-30, DTE 0, PCR 0.75). Do not edit the copy without re-checking
 * the shot — see tradepro-shots/SECTION2-SPEC.md.
 */
(function () {
  "use strict";

  var BASE = "/tp/s2/";

  /* Pill order matches Trade Pro's own Mode dropdown, not visual impact. */
  var MODES = [
    { key: "price", label: "Price", file: "oc-price.webp",
      note: "Six columns a side: volume, volume PCR, OI, OI change and LTP — " +
            "plus a trend read on every strike. LU, SB and SC tag long " +
            "unwinding, short buildup and short covering." },
    { key: "greeks", label: "Greeks", file: "oc-greeks.webp",
      note: "Theta, delta and IV per strike. Delta walks 1.00 to 0.00 across " +
            "the money — 0.99 at 24450, 0.01 by 24500 — and IV bottoms at " +
            "65.72 on the ATM row." },
    { key: "straddle", label: "Straddle", file: "oc-straddle.webp",
      note: "Both legs on one row. Total premium and both breakevens are " +
            "already worked out: 21.65 at the 24450 straddle, breaking even " +
            "at 24,471.65 and 24,428.35." },
    { key: "oi", label: "OI", file: "oc-oi.webp",
      note: "Open interest as bars — filled for the position, underlined for " +
            "the change. 2.88Cr sits on the 24500 call against 2.41Cr on the " +
            "24450 put." }
  ];

  function el(tag, cls, text) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }

  function img(file, alt, eager) {
    var n = document.createElement("img");
    n.src = BASE + file;
    n.alt = alt;
    n.decoding = "async";
    if (!eager) n.loading = "lazy";
    return n;
  }

  /* The section is identified by its own heading text, so this cannot latch
   * onto the wrong <section> if the page order changes. */
  function findSection() {
    var hs = document.querySelectorAll("h2");
    for (var i = 0; i < hs.length; i++) {
      if (/Online Stock Market Trading Platform/i.test(hs[i].textContent)) {
        return hs[i].closest("section");
      }
    }
    return null;
  }

  function build() {
    var section = findSection();
    if (!section || section.dataset.improved) return;

    var shell = section.querySelector(":scope > div") || section;

    var wrap = el("div", "s2");

    /* ---- heading ---- */
    var head = el("div", "s2-head");
    var h2 = el("h2", "text-[24px] md:text-[40px] lg:text-[48px] font-bold " +
      "text-[var(--global-text-2)] manrope-700 md:manrope-800 leading-tight",
      "Read the whole options book, then trade it from the chart");
    var lead = el("p", "s2-lead font-noto text-[var(--global-text-13)] " +
      "text-[14px] md:text-[16px] lg:text-[18px] leading-relaxed",
      "The option chain runs in four modes over one live tick. Expiry, strike " +
      "range, days to expiry and PCR stay pinned above every one of them.");
    head.appendChild(h2);
    head.appendChild(lead);
    wrap.appendChild(head);

    /* ---- mode switcher ---- */
    var tabs = el("div", "s2-modes");
    tabs.setAttribute("role", "tablist");
    tabs.setAttribute("aria-label", "Option chain mode");

    var frame = el("div", "s2-frame");
    var scroll = el("div", "s2-scroll");
    var rail = el("div", "s2-rail");
    var note = el("div", "s2-note");
    var currentMode = 0;
    var autoTimer = null;
    var userInteracted = false;

    function startAutoCarousel() {
      if (autoTimer) clearInterval(autoTimer);
      autoTimer = setInterval(function () {
        currentMode = (currentMode + 1) % MODES.length;
        select(currentMode);
      }, 3000);
    }

    function stopAutoCarousel() {
      if (autoTimer) clearInterval(autoTimer);
      autoTimer = null;
      userInteracted = true;
    }

    MODES.forEach(function (m, i) {
      var shot = img(m.file, "Trade Pro option chain, " + m.label + " mode",
                     i === 0);
      shot.className = "s2-shot" + (i === 0 ? " s2-on" : "");
      shot.id = "s2-shot-" + m.key;
      rail.appendChild(shot);

      var pill = el("button", "s2-mode", m.label);
      pill.type = "button";
      pill.setAttribute("role", "tab");
      pill.setAttribute("aria-selected", i === 0 ? "true" : "false");
      pill.setAttribute("aria-controls", shot.id);
      pill.tabIndex = i === 0 ? 0 : -1;
      pill.addEventListener("click", function () {
        stopAutoCarousel();
        currentMode = i;
        select(i);
      });
      pill.addEventListener("keydown", function (e) {
        var d = e.key === "ArrowRight" ? 1 : e.key === "ArrowLeft" ? -1 : 0;
        if (!d) return;
        e.preventDefault();
        stopAutoCarousel();
        currentMode = (i + d + MODES.length) % MODES.length;
        select(currentMode, true);
      });
      tabs.appendChild(pill);
    });

    function select(i, focus) {
      currentMode = i;
      MODES.forEach(function (m, j) {
        var on = i === j;
        rail.children[j].classList.toggle("s2-on", on);
        var pill = tabs.children[j];
        pill.setAttribute("aria-selected", on ? "true" : "false");
        pill.tabIndex = on ? 0 : -1;
        if (on && focus) pill.focus();
      });
      note.innerHTML = "";
      note.appendChild(el("b", null, MODES[i].label));
      note.appendChild(document.createTextNode(MODES[i].note));
    }

    scroll.appendChild(rail);
    frame.appendChild(scroll);
    wrap.appendChild(tabs);
    wrap.appendChild(frame);
    wrap.appendChild(el("p", "s2-hint",
      "Scroll the chain sideways to see every column."));
    wrap.appendChild(note);
    select(0);

    shell.innerHTML = "";
    shell.appendChild(wrap);
    section.dataset.improved = "s2";

    /* Start auto-carousel after a brief delay to ensure DOM is ready */
    setTimeout(startAutoCarousel, 1000);
  }

  function safeBuild() {
    try { build(); } catch (e) { console.warn("s2 failed", e); }
  }

  /* This page is heavy enough that `load` fires around 4-6s and the section
   * lands at 7-9s. A fixed retry window is therefore not enough on its own: if
   * React re-renders the section after the window closes, the node is replaced,
   * our dataset flag goes with it, and Section 2 reverts to the old prose for
   * good. So poll for a while AND watch the parent for the node being swapped. */
  function start() {
    safeBuild();
    var tries = 0;
    var iv = setInterval(function () {
      safeBuild();
      if (++tries > 25) clearInterval(iv);
    }, 400);

    if (typeof MutationObserver !== "function") return;
    var pending = 0;
    var obs = new MutationObserver(function () {
      // build() is a no-op once the flag is set, so this is cheap
      if (pending) return;
      pending = setTimeout(function () { pending = 0; safeBuild(); }, 120);
    });
    var host = document.querySelector("main") || document.body;
    obs.observe(host, { childList: true, subtree: true });
  }

  if (document.readyState === "complete") start();
  else window.addEventListener("load", start);
})();
